In [3]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv("roo_data.csv")

In [5]:
dataset.iloc[:,-1]

0                               Database Developer
1                             Portal Administrator
2                             Portal Administrator
3                   Systems Security Administrator
4                         Business Systems Analyst
5                        Software Systems Engineer
6                               Database Developer
7                    Business Intelligence Analyst
8                         Business Systems Analyst
9                          CRM Technical Developer
10                   Mobile Applications Developer
11                                     UX Designer
12                         CRM Technical Developer
13                        Business Systems Analyst
14                     Quality Assurance Associate
15                                   Web Developer
16                                   Web Developer
17                    Information Security Analyst
18                            CRM Business Analyst
19                    Informati

In [6]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
l=12
len(data[0])

38

In [7]:
dataset.iloc[:,14:38]

can work long time before system? self-learning capability?  \
0                                   yes                       yes   
1                                   yes                        no   
2                                   yes                        no   
3                                    no                       yes   
4                                    no                        no   
5                                   yes                       yes   
6                                    no                        no   
7                                   yes                        no   
8                                    no                       yes   
9                                    no                        no   
10                                  yes                        no   
11                                   no                       yes   
12                                  yes                        no   
13                                   no                        no   
14                                  yes                        no   
15                                  yes                       yes   
16                                   no                        no   
17                                   no                       yes   
18                                   no                        no   
19                                   no                       yes   
20                                  yes                       yes   
21                                  yes                       yes   
22                                   no                        no   
23                                   no                       yes   
24                                  yes                       yes   
25                                  yes                       yes   
26                                   no                       yes   
27                                  yes                       yes   
28                                  yes                        no   
29                                  yes                        no   
...                                 ...                       ...   
19970                               yes                       yes   
19971                                no                       yes   
19972                                no                       yes   
19973                                no                       yes   
19974                                no                        no   
19975                                no                        no   
19976                                no                        no   
19977                                no                       yes   
19978                               yes                        no   
19979                                no                        no   
19980                               yes                        no   
19981                                no                       yes   
19982                               yes                        no   
19983                                no                        no   
19984                                no                        no   
19985                               yes                       yes   
19986                                no                       yes   
19987                                no                        no   
19988                               yes                        no   
19989                               yes                        no   
19990                                no                        no   
19991                                no                       yes   
19992                               yes                        no   
19993                                no                        no   
19994                                no                       yes   
19995                               yes                        no   
1999

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
labelencoder = LabelEncoder()

In [10]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
        0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 1, 0, 1, 5,
        2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 1, 0, 1, 0,
        7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 0, 1, 0, 6, 1,
        1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1]],
      dtype=object)

In [11]:
dataset.iloc[:,:14]

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
5                                            88                        86   
6                                            93                        77   
7                                            84                        72   
8                                            73                        66   
9                                            62                        76   
10                                           73                        80   
11                                           63                        76   
12                                           63                        64   
13                                           68                        93   
14                                           90                        83   
15                                           94                        71   
16                                           60                        92   
17                                           92                        86   
18                                           82                        91   
19                                           90                        73   
20                                           67                        61   
21                                           65                        61   
22                                           84                        62   
23                                           74                        89   
24                                           92                        67   
25                                           75                        74   
26                                           90                        82   
27                                           71                        60   
28                                           83                        82   
29                                           83                        68   
...                                         ...                       ...   
19970                                        65                        84   
19971                                        88                        92   
19972                                        64                        74   
19973                                        64                        66   
19974                                        68                        61   
19975                                        84                        68   
19976                                        67                        69   
19977                                        88                        71   
19978                                        71                        73   
19979                                        60                        77   
19980                                        78                        64   
19981                                        80                        89   
19982                                        64                        94   
19983                                        80                        92   
19984                                        72                        69   
19985                                        65                        77   
19986                                        74                        72   
19987                                        82                        62   
19988                                        64                        85   
19989                                        73                        60   
199

In [12]:
data[:5,14:]

array([[1, 1, 1, 8, 0, 0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0,
        0, 1, 0],
       [1, 0, 1, 5, 2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0,
        0, 1],
       [1, 0, 1, 0, 7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1,
        0, 0, 1],
       [0, 1, 0, 6, 1, 1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1,
        1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0,
        1, 1]], dtype=object)

In [13]:
from sklearn.preprocessing import Normalizer

In [14]:
data1=data[:,:14]

In [15]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)


In [16]:
normalized_data

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.3430836 , 0.28934762, 0.33068299, ..., 0.02480122, 0.00826707,
        0.01240061],
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526]])

In [17]:
data2=data[:,14:]
data2.shape

(20000, 24)

In [18]:
df1 = np.append(normalized_data,data2,axis=1)
df1.shape

(20000, 38)

In [19]:
## adding headers

X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

X1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                  0.28509                 0.260299   
1                                  0.34998                 0.278189   
2                                 0.295012                 0.357339   
3                                 0.328025                 0.375503   
4                                 0.397157                 0.267649   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                           0.322276                           0.359461   
1                           0.327545                           0.269215   
2                           0.378115                           0.361494   
3                           0.258967                           0.362554   
4                           0.388523                           0.289234   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                        0.388383                           0.388383   
1                        0.318571                           0.314085   
2                        0.253461                           0.336563   
3                        0.384135                           0.315077   
4                        0.306502                           0.384206   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                            0.359461                  0.347066   
1                            0.327545                  0.376901   
2                            0.299168                  0.299168   
3                              0.2676                  0.379819   
4                            0.315136                  0.306502   

  Percentage in Communication skills Hours working per day  ...  \
0                           0.252036             0.0371856  ...   
1                            0.40831             0.0538431  ...   
2                            0.39058             0.0457062  ...   
3                           0.297812             0.0302129  ...   
4                           0.315136             0.0172677  ...   

  interested in games Interested Type of Books Salary Range Expected  \
0                   0                       21                     1   
1                   1                        5                     1   
2                   1                       29                     0   
3                   0                       23                     0   
4                   1                        7                     1   

  In a Realtionship? Gentle or Tuff behaviour? Management or Technical  \
0                  0                         1                       0   
1                  1                         0                       1   
2                  0                         1                       0   
3                  1                         0                       0   
4                  0                         1                       0   

  Salary/work hard/smart worker worked in teams ever? Introvert  
0           0                 0                     1         0  
1           0                 0                     0         1  
2           1                 0                     0         1  
3           1                 1                     1         1  
4           1                 0                     1         1  

[5 rows x 38 columns]

In [20]:
label1=dataset.iloc[:,-1]

In [21]:
label1

0                               Database Developer
1                             Portal Administrator
2                             Portal Administrator
3                   Systems Security Administrator
4                         Business Systems Analyst
5                        Software Systems Engineer
6                               Database Developer
7                    Business Intelligence Analyst
8                         Business Systems Analyst
9                          CRM Technical Developer
10                   Mobile Applications Developer
11                                     UX Designer
12                         CRM Technical Developer
13                        Business Systems Analyst
14                     Quality Assurance Associate
15                                   Web Developer
16                                   Web Developer
17                    Information Security Analyst
18                            CRM Business Analyst
19                    Informati

In [22]:
arr=np.unique(label1)

In [23]:
Dict = {}
for i in range(0,34): 
    Dict[arr[i]] = i

In [24]:
Dict

{'Applications Developer': 0,
 'Business Intelligence Analyst': 1,
 'Business Systems Analyst': 2,
 'CRM Business Analyst': 3,
 'CRM Technical Developer': 4,
 'Data Architect': 5,
 'Database Administrator': 6,
 'Database Developer': 7,
 'Database Manager': 8,
 'Design & UX': 9,
 'E-Commerce Analyst': 10,
 'Information Security Analyst': 11,
 'Information Technology Auditor': 12,
 'Information Technology Manager': 13,
 'Mobile Applications Developer': 14,
 'Network Engineer': 15,
 'Network Security Administrator': 16,
 'Network Security Engineer': 17,
 'Portal Administrator': 18,
 'Programmer Analyst': 19,
 'Project Manager': 20,
 'Quality Assurance Associate': 21,
 'Software Developer': 22,
 'Software Engineer': 23,
 'Software Quality Assurance (QA) / Testing': 24,
 'Software Systems Engineer': 25,
 'Solutions Architect': 26,
 'Systems Analyst': 27,
 'Systems Security Administrator': 28,
 'Technical Engineer': 29,
 'Technical Services/Help Desk/Tech Support': 30,
 'Technical Support': 

In [25]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [26]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   7
1                  18
2                  18
3                  28
4                   2

# Decision Tree Classifier

In [27]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10) 

In [28]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [30]:
y_pred = clf.predict(X_test)

In [31]:
y_pred

array([27, 29, 15, ...,  2, 29, 28])

In [32]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [33]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*1000)

confusion matrics= [[4 4 1 ... 3 4 2]
 [3 3 1 ... 5 2 6]
 [3 3 2 ... 2 0 5]
 ...
 [4 1 4 ... 0 1 6]
 [4 3 1 ... 5 4 4]
 [5 4 1 ... 5 1 3]]
  
accuracy= 26.5


# With entropy

In [34]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
            splitter='best')

In [35]:
entropy_y_pred=clf_entropy.predict(X_test)

In [36]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [37]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [38]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",l*entropy_accuracy*100)

confusion matrics= [[1 3 7 ... 3 2 2]
 [2 4 3 ... 3 2 4]
 [1 2 4 ... 0 3 1]
 ...
 [1 6 3 ... 0 5 2]
 [3 2 4 ... 2 2 4]
 [5 1 6 ... 6 6 4]]
  
accuracy= 32.4


# Support Vector Machines

In [39]:
from sklearn import svm

In [40]:
clf = svm.SVC()
clf.fit(X_train, y_train)

C:\Users\Sandeep Chinnareddy\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Sandeep Chinnareddy\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [41]:
svm_y_pred = clf.predict(X_test)

In [42]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [43]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",l*svm_accuracy*100)

confusion matrics= [[0 0 1 ... 1 1 0]
 [0 0 4 ... 0 0 0]
 [1 0 2 ... 0 0 0]
 ...
 [0 0 1 ... 0 1 0]
 [0 0 2 ... 0 0 0]
 [0 1 2 ... 0 1 0]]
  
accuracy= 62.1


# XGBoost

In [94]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10) 

In [95]:
X_train.shape

(14000, 38)

In [96]:
X_train=pd.to_numeric(X_train.values.flatten())

In [97]:
X_train=X_train.reshape((14000,38))

In [98]:
from xgboost import XGBClassifier

In [99]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [100]:
xgb_y_pred = clf.predict(X_test)

In [101]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)

In [102]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",l*xgb_accuracy*100)

confusion matrics= [[1 0 1 ... 1 1 0]
 [1 0 4 ... 0 0 0]
 [1 0 7 ... 2 0 0]
 ...
 [0 0 1 ... 2 1 0]
 [0 0 2 ... 0 3 0]
 [0 1 3 ... 0 1 0]]
  
accuracy= 83.60000000000001


# CHATBOT

In [44]:
import io
import random
import string
import warnings
import numpy as np
import pandas as pd

In [45]:
from sklearn import decomposition
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
'''
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()
'''

'\nimport nltk\nimport ssl\n\ntry:\n    _create_unverified_https_context = ssl._create_unverified_context\nexcept AttributeError:\n    pass\nelse:\n    ssl._create_default_https_context = _create_unverified_https_context\n\nnltk.download()\n'

In [48]:
import nltk
from nltk.stem import WordNetLemmatizer
#nltk.download('popular', quiet=True)
f=open('chatbot.txt','r',errors = 'ignore')
RawData=f.read()
RawData = RawData.lower()

In [49]:
sent_tokens = nltk.sent_tokenize(RawData)# converts to list of sentences 
word_tokens = nltk.word_tokenize(RawData)# converts to list of words

In [50]:
lemmer = nltk.stem.WordNetLemmatizer()
#WordNet is a semantically-oriented dictionary of English included in NLTK.
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [51]:
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey",)
GREETING_RESPONSES = ["Oy' mate! can i help you out today?", "Hello buddy! can i help you out today?", "*nods*", "Saheli at your service", "hello friend. can i help you out today?", "i am glad that you are talking to me"]

def greeting(sentence):
 
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)

In [52]:
#Various Responses out of which a random one will be picked
QUESTIONAIRE_Qs = ("What is your percentage in Operating Systems?" , "What about in Data Structures and Algorithms?" , "What about in Programming Concepts?" , "What about in in Software Engineering?", "What is your percentage in Computer Networks?", "What is your percentage in Electronics subjects?" , "What is your percentage in Computer Architecture?" , "What is your percentage in Mathematics?" , "What is your percentage in Communication skills?" , "How many hours working per day?" , "Rate your Logical quotient out of 10!" , " Number of hackathons attended?" ," Rate your Coding skills." , " Rate your Public speaking skills out of 10" , " Can you work for long time before system?" , "Can you learn things on your own?" , "Do you have interest in extra-curriculars?" , "What interests you more, Machine Learning or app development?" , "Choose one: Cloud computing, database security, game development, hacking, testing, data science!" , " Did you take any talent tests?" , " Did you attend any olympiads?" , "What best describes your Reading and writing skills: Excellent, medium or poor" , "What best describes your memory skills: Excellent, medium or poor" , "Name the most interesting subject you are interested in CS" , "Do you see yourself as a developer or a Business process analyst?" , "Would you prefer job or higherstudies?","What type of company do you want to work in?", "Have you taken any inputs from any seniors?", "Are you interested in games?","What kind of books are you into? because that matters too! :P", "Would you prefer work or salary?", "Do you have other commitments like clubs and departments?", "What do you think best describes you best: gentle or stubborn?", "Which one of the following are you more inclined towards: Management or technical?", "Would you prefer work or salary?", "Are you a hard worker or a smart worker?", "Do you like working in teams?", "Are you an introvert?")
GREAT_WORK = ("That's amazing! ", "I'm proud of you! ", "wow! ", "Damn! Nice dude!", "Hey that's pretty awesome if you ask me! ","Noice! ","Lovely! ","Such a good kid! ",)
MEDIUM_WORK = ("hey not bad! ","Okay alright! ", "Shouldn't be that big a problem! ", "Oh acha, okay! ", "That's where most of us lie, right? haha! ")
POOR_WORK = ("Don't worry! ", "Ouch!! ", "OOPS! ", "Somebody wasn't paying attention, huh? ", "Oh no..", "That's bad dude! ", "It's okay, you can work on that! ",)
FINAL_ANSWER = ("That's the end of this quiz! After a lot of thinking, I think you should become a ", "We've come to the end of the quiz! My research suggests that you should become a ", "In my opinion, you should actually consider becoming a ", " My Final say is, You're best suited for the role of a ", "You must be wondering what I found out! You should definitely be a ", "That's the end of this quiz! After extenive research of your personal choices and academic backgroun, you should definitely be a ")

In [ ]:
flag = True
 
relative_response = " "

in_quiz = False
collect_answer = False
percentage_question = True
question_no = -1;

ANSWERS = []

print("SAHELI: Hey")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("SAHELI: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("SAHELI: "+ "My name is Saheli. I aim to help you out with career guidance. If you want to exit, type Bye!" + greeting(user_response) + "! I believe you're confused about your ideal job role. If you want to take a quick questionnaire, type 'start'")

        if(user_response=='start'):
            in_quiz = True
            print("SAHELI: Great, Let's begin the quiz then")
            
        if(user_response.isdigit()):
            if(percentage_question):
                if(int(user_response) < 40):
                    relative_response = random.choice(POOR_WORK)
                if((int(user_response) < 60) & (int(user_response) > 40)):
                    relative_response = random.choice(MEDIUM_WORK)
                if(int(user_response) > 60):
                    relative_response = random.choice(GREAT_WORK)
            else:
                if(int(user_response) > 6):
                    relative_response = random.choice(GREAT_WORK)
                if((int(user_response) < 6) & (int(user_response) > 4)):
                    relative_response = random.choice(MEDIUM_WORK)
                if(int(user_response) < 4):
                    relative_response = random.choice(POOR_WORK)
        if(in_quiz):
            ####store the given answer in an array"
            ######################################
            ANSWERS.append(user_response)
            
            question_no = question_no + 1
            if(question_no == 38):
                in_quiz = False
                ###Call model with stored value"
                ###############################
                ###############################
                print("Saheli: WELL DONE!!")
                ANSWERS.remove('start')
                for i in range(14,38):
                    ANSWERS[14:38] = labelencoder.fit_transform(ANSWERS[14:38])
                for i in range(0,14):
                    ANSWERS[i]= int(ANSWERS[i])
                ANSWERS_ARRAY = np.asarray(ANSWERS)
                data123=data
                ANS=ANSWERS_ARRAY
                ANS.reshape(1,38)
                ANS1=np.reshape(ANS,(1,38))
                new_data = np.append(data123,ANS1,axis=0)
                new_data_for_normalization = new_data[:,:14]
                normalized_data_for_prediction = Normalizer().fit_transform(new_data_for_normalization)
                print(normalized_data_for_prediction.shape)
                remaining_data = new_data[:,14:]
                new_df = np.append(normalized_data_for_prediction,remaining_data,axis=1)
                prediction_array = new_df[20000,:]
                prediction_array.reshape(1,-1)
                prediction_array2d= [prediction_array]
                clf = svm.SVC()
                clf.fit(X_train, y_train)
                predicted_value = clf.predict(prediction_array2d)
                
                
                print(random.choice(FINAL_ANSWER) + list(Dict.keys())[list(Dict.values()).index(predicted_value[0])] )
                data123=data
                ANS=ANSWERS_ARRAY
                #predict the output of the model using ANSWERS
                
                print("Saheli: Thank you for taking this quiz, please say 'bye' to exit")
                
                
            if(question_no > 8):
                percentage_question = False
            print("SAHELI: " + relative_response + QUESTIONAIRE_Qs[question_no])

            collect_answer = True
            relative_response = ""
            
    else:
        flag=False
        print("SAHELI: Bye! take care..")
        
  
        

SAHELI: Hey
ya
i am here
hello
SAHELI: My name is Saheli. I aim to help you out with career guidance. If you want to exit, type Bye!hello friend. can i help you out today?! I believe you're confused about your ideal job role. If you want to take a quick questionnaire, type 'start'
what is your name
start
SAHELI: Great, Let's begin the quiz then
SAHELI:  What is your percentage in Operating Systems?
seventy five
SAHELI: What about in Data Structures and Algorithms?
forty
SAHELI: What about in Programming Concepts?
seven
SAHELI: What about in in Software Engineering?
five
SAHELI: What is your percentage in Computer Networks?
two
SAHELI: What is your percentage in Electronics subjects?
5000
SAHELI: Lovely! What is your percentage in Computer Architecture?


In [54]:
print(ANSWERS)

[67, 83, 86, 63, 82, 71, 70, 64, 78, 8, 9, 0, 5, 8, 14, 14, 8, 6, 12, 14, 8, 9, 2, 7, 10, 5, 0, 14, 14, 1, 13, 8, 3, 11, 13, 4, 14, 8]


In [55]:
print(len(ANSWERS))

38


In [56]:
for i in range(14,38):
    ANSWERS[14:38] = labelencoder.fit_transform(ANSWERS[14:38])

In [57]:
print(ANSWERS)

[67, 83, 86, 63, 82, 71, 70, 64, 78, 8, 9, 0, 5, 8, 14, 14, 8, 6, 12, 14, 8, 9, 2, 7, 10, 5, 0, 14, 14, 1, 13, 8, 3, 11, 13, 4, 14, 8]


In [58]:
for i in range(0,14):
    ANSWERS[i]= int(ANSWERS[i])

In [59]:
print(ANSWERS)

[67, 83, 86, 63, 82, 71, 70, 64, 78, 8, 9, 0, 5, 8, 14, 14, 8, 6, 12, 14, 8, 9, 2, 7, 10, 5, 0, 14, 14, 1, 13, 8, 3, 11, 13, 4, 14, 8]


In [60]:
type(ANSWERS)

list

In [61]:
type(data)

numpy.ndarray

In [62]:
data.shape

(20000, 38)

In [63]:
ANSWERS_ARRAY = np.asarray(ANSWERS)

In [66]:
ANSWERS_ARRAY

array([67, 83, 86, 63, 82, 71, 70, 64, 78,  8,  9,  0,  5,  8, 14, 14,  8,
        6, 12, 14,  8,  9,  2,  7, 10,  5,  0, 14, 14,  1, 13,  8,  3, 11,
       13,  4, 14,  8], dtype=int64)

In [67]:
type(ANSWERS_ARRAY)

numpy.ndarray

In [68]:
data123=data
ANS=ANSWERS_ARRAY

In [69]:
data123.shape

(20000, 38)

In [70]:
ANS.shape

(38,)

In [71]:
ANS.reshape(1,38)

array([[67, 83, 86, 63, 82, 71, 70, 64, 78,  8,  9,  0,  5,  8, 14, 14,
         8,  6, 12, 14,  8,  9,  2,  7, 10,  5,  0, 14, 14,  1, 13,  8,
         3, 11, 13,  4, 14,  8]], dtype=int64)

In [72]:
ANS.shape

(38,)

In [73]:
ANS1=np.reshape(ANS,(1,38))

In [74]:
ANS1.shape

(1, 38)

In [75]:
new_data = np.append(data123,ANS1,axis=0)

In [76]:
new_data

array([[69, 63, 78, ..., 0, 1, 0],
       [78, 62, 73, ..., 0, 0, 1],
       [71, 86, 91, ..., 0, 0, 1],
       ...,
       [68, 87, 91, ..., 1, 1, 0],
       [73, 77, 74, ..., 0, 1, 0],
       [67, 83, 86, ..., 4, 14, 8]], dtype=object)

In [77]:
new_data_for_normalization = new_data[:,:14]

In [78]:
new_data_for_normalization.shape

(20001, 14)

In [79]:
normalized_data_for_prediction = Normalizer().fit_transform(new_data_for_normalization)
print(normalized_data_for_prediction.shape)

(20001, 14)


In [80]:
normalized_data_for_prediction

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526],
       [0.30016788, 0.37184977, 0.38529012, ..., 0.        , 0.02240059,
        0.03584094]])

In [81]:
remaining_data = new_data[:,14:]
remaining_data.shape

(20001, 24)

In [82]:
new_df = np.append(normalized_data_for_prediction,remaining_data,axis=1)
new_df.shape

(20001, 38)

In [83]:
prediction_array = new_df[20000,:]

In [84]:
prediction_array

array([0.30016788419312196, 0.3718497669855093, 0.3852901200090819,
       0.28224741349502513, 0.3673696493109851, 0.3180883548912188,
       0.31360823721669456, 0.28672753116954935, 0.34944917861288827,
       0.03584094139619367, 0.040321059070717875, 0.0,
       0.02240058837262104, 0.03584094139619367, 14, 14, 8, 6, 12, 14, 8,
       9, 2, 7, 10, 5, 0, 14, 14, 1, 13, 8, 3, 11, 13, 4, 14, 8],
      dtype=object)

In [85]:
prediction_array.shape

(38,)

In [86]:
prediction_array.reshape(1,-1)

array([[0.30016788419312196, 0.3718497669855093, 0.3852901200090819,
        0.28224741349502513, 0.3673696493109851, 0.3180883548912188,
        0.31360823721669456, 0.28672753116954935, 0.34944917861288827,
        0.03584094139619367, 0.040321059070717875, 0.0,
        0.02240058837262104, 0.03584094139619367, 14, 14, 8, 6, 12, 14,
        8, 9, 2, 7, 10, 5, 0, 14, 14, 1, 13, 8, 3, 11, 13, 4, 14, 8]],
      dtype=object)

In [87]:
prediction_array2d= [prediction_array]

In [88]:
clf = svm.SVC()
clf.fit(X_train, y_train)
predicted_value = clf.predict(prediction_array2d)


In [89]:
predicted_value

array([16])

In [90]:
predicted_value[0]

16

In [91]:
y.iloc[46,:]

Suggested Job Role    16
Name: 46, dtype: int32

In [92]:
key_list = list(Dict.keys()) 
val_list = list(Dict.values())

In [93]:
print(list(Dict.keys())[list(Dict.values()).index(predicted_value[0])]) 

Network Security Administrator
